### ISSUE TITLE
Welcome to asmalltalk.com

### ISSUE THREAD

**Issue by metrue** [metrue/asmalltalk.com#66]
.

              
      
                            

                                                Makers
                
                                        **   Let's connect   **
                  

                                                    .
                     
                   
> Text something here with the code generated by https://asmalltalk.com,  get an email introduction to a fellow Github member every day or week                    
> 留言附带你在 https://asmalltalk.com 上生成的验证码，小对话 每天会匹配一位好友，然后发送一封包含她/他的简介到你的邮箱中.

**Comment by metrue** [comment]
dfdfd

**Comment by CN-Lyc** [comment]
#asmalltalklZ2aVV

**Comment by ferocknew** [comment]
#asmalltalkJdjeZZ

**Comment by xhp281** [comment]
#asmalltalklZ2aVV

**Comment by pplam** [comment]
#asmalltalklZ2aVV

**Comment by metrue** [comment]
@CN-Lyc @ferocknew @xhp281 @pplam fixed. PR https://github.com/metrue/asmalltalk.com/pull/114/files

**Comment by pplam** [comment]
#asmalltalklZ2aVV

**Comment by NodeMirai** [comment]
#asmalltalklZ2aVV

**Comment by wloolw** [comment]
#asmalltalklZ2aVV

**Comment by baiheinet** [comment]
#asmalltalklZ2aVV

**Comment by waynecz** [comment]
#asmalltalklZ2aVV

**Comment by biezhi** [comment]
#asmalltalklZ2aVV

**Comment by 1393925530** [comment]
#asmalltalklZ2aVV

**Comment by Armour-warrior** [comment]
#asmalltalklZ2aVV

**Comment by Armour-warrior** [comment]
#asmalltalklZ2aVV

**Comment by metrue** [comment]
@Armour-warrior You did not register successfully? Please notice that the id you input in https://asmalltalk.com is Your Github ID.

**Comment by Armour-warrior** [comment]
我试过好多次了，一直成功不了，你知道是怎么回事吗？🙏




| |
向晋利
邮箱：xiangjinli123456@163.com
|

签名由 网易邮箱大师 定制

On 06/07/2018 14:26, DONGHAO.LI wrote:

#asmalltalklZ2aVV

**Comment by Hasaki1997** [comment]
#asmalltalklZ2aVV

**Comment by metrue** [comment]
@Armour-warrior 
相信你已经收到确认邮件。

**Comment by juzhiyuan** [comment]
#asmalltalklZ2aVV

**Comment by tt67wq** [comment]
#asmalltalklZ2aVV

**Comment by changkun** [comment]
#asmalltalklZ2aVV

**Comment by csssong** [comment]
#asmalltalklZ2aVV

**Comment by metrue** [comment]
Hi, All

I am closing https://asmalltalk.com now. if anyone is interested in this project and wants to take over, I am glad to provide any kind of help if I can.
